// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLTjarQCnTwU5Lu-JyFBMosoor5PmkvTs',
    appId: '1:90543283572:web:01262231e7658c4de56021',
    messagingSenderId: '90543283572',
    projectId: 'nikestore-39b37',
    authDomain: 'nikestore-39b37.firebaseapp.com',
    storageBucket: 'nikestore-39b37.appspot.com',
    measurementId: 'G-K5NH2HZL5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFFgnsCCP1DlyvdoSTAB-NEWIw4cwsjcc',
    appId: '1:90543283572:android:fe98ada175d77d76e56021',
    messagingSenderId: '90543283572',
    projectId: 'nikestore-39b37',
    storageBucket: 'nikestore-39b37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2syBBvt8FVcJig-mRpDzllprZ7OQ5-4',
    appId: '1:90543283572:ios:803a73879ce6746ee56021',
    messagingSenderId: '90543283572',
    projectId: 'nikestore-39b37',
    storageBucket: 'nikestore-39b37.appspot.com',
    iosBundleId: 'com.example.nikeStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK2syBBvt8FVcJig-mRpDzllprZ7OQ5-4',
    appId: '1:90543283572:ios:803a73879ce6746ee56021',
    messagingSenderId: '90543283572',
    projectId: 'nikestore-39b37',
    storageBucket: 'nikestore-39b37.appspot.com',
    iosBundleId: 'com.example.nikeStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLTjarQCnTwU5Lu-JyFBMosoor5PmkvTs',
    appId: '1:90543283572:web:71e71e0ccf1a27c1e56021',
    messagingSenderId: '90543283572',
    projectId: 'nikestore-39b37',
    authDomain: 'nikestore-39b37.firebaseapp.com',
    storageBucket: 'nikestore-39b37.appspot.com',
    measurementId: 'G-T6JHJMDRV3',
  );
}
